# Skład grupy:
## Paweł Awramiuk
## Anna Chojnowska
## Piotr Grusza
## Szymon Leszczyński

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.kernel_ridge import KernelRidge

In [11]:
data_ALL = pd.read_csv("data_ALL.csv")
data_ALL.drop(columns=['Unnamed: 0'], inplace=True)
data_ALL

squareMeters     rooms     floor  floorCount  buildYear  latitude  \
0         -0.586083 -0.740848  0.144321    0.637270   0.998324 -1.458914   
1         -0.824275 -0.740848 -0.584870   -0.732352   0.998324 -1.457078   
2          0.783521  0.553680  0.144321   -1.188893  -0.018122 -1.427091   
3          1.021713  0.553680  0.144321   -0.275811  -0.018122 -1.462786   
4         -0.115654 -0.740848 -1.314060   -1.188893  -0.018122 -1.410468   
...             ...       ...       ...         ...        ...       ...   
35075      2.510413  0.553680  0.144321   -0.732352  -2.465123  1.051293   
35076      2.093577  1.848208 -0.584870   -1.188893   0.923032  1.055351   
35077      2.230537  1.848208  0.144321   -1.188893  -2.013369  1.048507   
35078      2.290085  1.848208  0.144321   -1.188893   0.283047  1.044252   
35079     -0.340745 -0.740848 -1.314060   -1.645434   0.057170  1.055325   

       longitude  centreDistance  poiCount  hasParkingSpace  ...  \
0       0.104722        0.569461 -0.783724                0  ...   
1       0.114647        0.256607 -0.878584                0  ...   
2       0.129172       -1.431261  0.734028                0  ...   
3       0.178690        1.102472 -0.499146                0  ...   
4       0.133610       -1.095232  2.062062                1  ...   
...          ...             ...       ...              ...  ...   
35075  -1.066714       -1.539408  3.295236                0  ...   
35076  -1.045404       -0.639469 -0.119707                1  ...   
35077  -1.076651       -1.550995  1.398045                0  ...   
35078  -1.099131       -0.593120 -0.499146                0  ...   
35079  -1.069560       -1.427398  2.631219                1  ...   

       city_katowice  city_krakow  city_lodz  city_lublin  city_poznan  \
0                  0            1          0            0            0   
1                  0            1          0            0            0   
2                  0            1          0            0            0   
3                  0            1          0            0            0   
4                  0            1          0            0            0   
...              ...          ...        ...          ...          ...   
35075              0            0          0            0            0   
35076              0            0          0            0            0   
35077              0            0          0            0            0   
35078              0            0          0            0            0   
35079              0            0          0            0            0   

       city_radom  city_rzeszow  city_szczecin  city_warszawa  city_wroclaw  
0               0             0              0              0             0  
1               0             0              0              0             0  
2               0             0              0              0             0  
3               0             0              0              0             0  
4               0             0              0              0             0  
...           ...           ...            ...            ...           ...  
35075           0             0              0              0             0  
35076           0             0              0              0             0  
35077           0             0              0              0             0  
35078           0             0              0              0             0  
35079           0             0              0              0             0  

[35080 rows x 33 columns]

In [12]:
features = data_ALL
labels = features.pop('price')

features = features.to_numpy()
labels = labels.to_numpy()

# Kernel Ridge

In [4]:
model = KernelRidge()
model.fit(features, labels)

KernelRidge()

In [5]:
def accuracy(model, data_X, data_y):
    err_sum = 0.0
    for i in range(len(data_X)):
        X = data_X[i].reshape(1, -1)  # one-item batch
        y = data_y[i]
        pred = model.predict(X)       # predicted income
        err_sum +=abs((y - pred) / y)
    err_sum /= len(data_y)
    return err_sum

In [6]:
accuracy(model, features, labels)

array([0.17483954])

# Decision trees

In [7]:
from sklearn import tree
model = tree.DecisionTreeRegressor()
model = model.fit(features, labels)
accuracy(model, features, labels)

array([0.00013319])

# Nearest neighbors regression

In [13]:
from sklearn import neighbors
n_neighbors = 5

model = neighbors.KNeighborsRegressor(n_neighbors, weights='distance')
model.fit(features, labels)
accuracy(model, features, labels)

array([0.00013333])